---
- name: Install GitLab GPG key
  rpm_key:
    state: present
    key: https://packages.gitlab.com/gpg.key
  when: ansible_os_family == 'RedHat'

- name: Install GitLab Runner dependencies
  yum:
    name: '{{ gitlab_runner_packages }}'
    state: present

- name: Enable and start docker
  systemd:
      name: docker
      state: started
      enabled: true

- name: Add GitLab Runner rpm repo
  template:
    src: runner_gitlab-ci-multi-runner.repo.j2
    dest: /etc/yum.repos.d/runner_gitlab-ci-multi-runner.repo

- name: Install GitLab Runner
  yum:
    name: gitlab-runner
    state: present
    update_cache: yes
  register: installinfo

- name: Set concurrent option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: ^concurrent =
    line: concurrent = {{ gitlab_runner_concurrent }}
    state: present
  notify: Restart gitlab-runner

- name: Register runner to GitLab
  command: gitlab-runner register >
    --non-interactive
    --url '{{ gitlab_runner_coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ gitlab_runner_description }}'
    --tag-list '{{ gitlab_runner_tags | join(",") }}'
    --executor '{{ gitlab_runner_executor }}'
    --docker-image '{{ gitlab_runner_docker_image }}'
    {% if gitlab_runner_privileged == true %}
    --docker-privileged
    {% endif %}
    {% gitlab_runner_allow_untagged %}
    --run-untagged
    {% endif %}
  when: installinfo.changed == true

- name: Start gitlab-runner service
  systemd:
      name: gitlab-runner
      state: started
      enabled: true
